import {z} from 'zod';
export const modes=['Technology','Feedstock','Sustainability','Commercial'] as const;
export const categories=['Technology','Feedstocks','Commercial','Sustainability','Projects','Patents','Technical readiness','FAQs','Case studies','Website','Pitch decks','White papers'] as const;
export const assessmentSchema=z.object({feedstock:z.string().min(2).max(100),tonnes:z.coerce.number().positive().max(100000000),country:z.string().min(2).max(100),moisture:z.coerce.number().min(0).max(100),characteristics:z.string().max(2000),pathway:z.enum(['syngas','hydrogen','co'])});
export const factorSchema=z.object({name:z.string().min(3),feedstock:z.string().min(2),country:z.string().min(2),source_id:z.string().uuid(),approved:z.boolean(),currency:z.string().regex(/^[A-Z]{3}$/),min_tonnes:z.number().nonnegative(),max_tonnes:z.number().positive(),min_moisture:z.number().min(0).max(100),max_moisture:z.number().min(0).max(100),assumptions:z.string().min(20),values:z.object({syngas:z.number().nonnegative(),hydrogen:z.number().nonnegative(),co:z.number().nonnegative(),syngas_price:z.number().nonnegative(),hydrogen_price:z.number().nonnegative(),co_price:z.number().nonnegative(),gate_fee:z.number(),opex_per_tonne:z.number().nonnegative(),capex:z.number().positive(),carbon_savings:z.number(),uncertainty_percent:z.number().min(0).max(100)})}).refine(f=>f.max_tonnes>=f.min_tonnes&&f.max_moisture>=f.min_moisture,'Invalid operating envelope');
export type Factor=z.infer<typeof factorSchema>;
export function calculate(input:z.infer<typeof assessmentSchema>,factor:Factor|null){
 if(!factor||!factor.approved||factor.feedstock.toLowerCase()!==input.feedstock.toLowerCase()||factor.country.toLowerCase()!==input.country.toLowerCase()||input.tonnes<factor.min_tonnes||input.tonnes>factor.max_tonnes||input.moisture<factor.min_moisture||input.moisture>factor.max_moisture)return {status:'awaiting_validation',message:'No NZP-approved model matches this feedstock, country and operating envelope. An NZP engineer must validate the characteristics before a numerical assessment is available.',outputs:null};
 const v=factor.values,t=input.tonnes;const products={syngas:t*v.syngas,hydrogen:t*v.hydrogen,co:t*v.co};const revenue=products[input.pathway]*v[`${input.pathway}_price`]+t*v.gate_fee;const profit=revenue-t*v.opex_per_tonne;
 return {status:'indicative',message:'Indicative screening only. Product yields represent alternative output pathways; revenue uses only the selected pathway. ROI is annual operating surplus / capital cost, before financing, tax and depreciation. Characteristics beyond moisture require engineering review. This is not an investment decision or performance guarantee.',outputs:{...products,revenue,carbon:t*v.carbon_savings,roi:profit/v.capex*100,payback:profit>0?v.capex/profit:null},uncertainty_percent:v.uncertainty_percent,currency:factor.currency,assumptions:factor.assumptions,model:factor.name,source_id:factor.source_id};
}
