import {NextRequest,NextResponse} from 'next/server';
import {z} from 'zod';
import {embedMany,gateway} from 'ai';
import {admin,db,failure} from '@/lib/server';
import {categories,factorSchema,modes} from '@/lib/model';
export const maxDuration=60;
const tables=['sources','coefficients','faqs','leads','expert_modes'] as const;
const sourceSchema=z.object({title:z.string().min(3).max(200),category:z.enum(categories),content:z.string().min(30).max(100000),public_url:z.url().refine(u=>u.startsWith('https://')),approved:z.boolean(),public_allowed:z.boolean(),review_note:z.string().min(10).max(2000)});
export async function GET(req:NextRequest){try{await admin(req);const table=z.enum(tables).parse(req.nextUrl.searchParams.get('table'));const {data,error}=await db().from(table).select('*').order('updated_at',{ascending:false}).limit(200);if(error)throw error;return NextResponse.json({data});}catch(e){return failure(e)}}
export async function POST(req:NextRequest){try{const reviewer=await admin(req);const body=await req.json();const table=z.enum(tables).parse(body.table);if(table==='leads')throw new Error('Leads are read-only');let row:Record<string,unknown>;if(table==='sources'){row=sourceSchema.parse(body.row);if(row.approved&&!row.public_allowed)throw new Error('Public permission required');}else if(table==='coefficients'){row=factorSchema.parse(body.row);if(row.approved){const {data}=await db().from('sources').select('id').eq('id',row.source_id).eq('approved',true).eq('public_allowed',true).single();if(!data)throw new Error('Approve coefficient evidence first');}}else if(table==='expert_modes'){row=z.object({name:z.enum(modes),prompt:z.string().min(20).max(4000),enabled:z.boolean()}).parse(body.row)}else{row=z.object({question:z.string().min(8).max(500),answer:z.string().min(10).max(5000),source_id:z.string().uuid(),approved:z.boolean()}).parse(body.row);if(row.approved){const {data}=await db().from('sources').select('id').eq('id',row.source_id).eq('approved',true).eq('public_allowed',true).single();if(!data)throw new Error('Approve FAQ evidence first');}}
 if(table==='faqs'&&row.approved){if(!process.env.EMBEDDING_MODEL||!process.env.AI_GATEWAY_API_KEY)throw new Error('Embedding service not configured');const {embeddings}=await embedMany({model:gateway.embeddingModel(process.env.EMBEDDING_MODEL),values:[`${row.question}\n${row.answer}`]});row.embedding=embeddings[0];}
 if(body.row.id)row.id=z.string().uuid().parse(body.row.id);row.updated_at=new Date().toISOString();row.reviewed_by=reviewer;
 let chunks:{content:string;locator:string;embedding:number[]}[]=[];
 if(table==='sources'&&row.approved){if(!process.env.EMBEDDING_MODEL||!process.env.AI_GATEWAY_API_KEY)throw new Error('Embedding service not configured');const text=row.content as string;const pieces=[];for(let offset=0;offset<text.length;offset+=1200)pieces.push(text.slice(offset,offset+1500));const {embeddings}=await embedMany({model:gateway.embeddingModel(process.env.EMBEDDING_MODEL),values:pieces});chunks=pieces.map((content,i)=>({content,locator:`Extract ${i+1}`,embedding:embeddings[i]}));}
 const {data,error}=await db().from(table).upsert(row).select().single();if(error)throw error;
 if(table==='sources'){const {error:chunkError}=await db().rpc('replace_source_chunks',{source_uuid:data.id,new_chunks:chunks});if(chunkError){await db().from('sources').update({approved:false}).eq('id',data.id);throw chunkError;}}
 const {error:auditError}=await db().from('audit_log').insert({actor:reviewer,entity:table,entity_id:data.id,action:row.approved?'approve':'save'});if(auditError)throw auditError;return NextResponse.json({saved:true,id:data.id});}catch(e){return failure(e)}}
