'use client';
import {useState,useEffect,FormEvent} from 'react';
import {ArrowUpRight,ArrowRight,Atom,Leaf,Layers3,ChartNoAxesCombined,ShieldCheck,Plus,MessageSquare,Send,FileText,ChevronRight,X,CheckCircle2} from 'lucide-react';
import {modes} from '@/lib/model';
type Citation={id:string;title:string;url:string;locator:string;excerpt:string};
type Message={question:string;answer:string;citations:Citation[]};
const modeInfo=[{icon:Atom,desc:'Understand the process',question:'How does NZP plasma gasification produce syngas?'},{icon:Layers3,desc:'Explore material suitability',question:'What information does NZP need to assess municipal waste?'},{icon:Leaf,desc:'Explore environmental outcomes',question:'How does NZP assess carbon reduction for a project?'},{icon:ChartNoAxesCombined,desc:'Build the commercial case',question:'What are the potential revenue streams for an NZP project?'}];
const wasteTypes=['Municipal waste','RDF','Plastics','Biomass','Agricultural waste','Hazardous waste','Other'];
async function request(path:string,body:unknown){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Unable to complete your request');return data;}
export default function Experience({compact=false}:{compact?:boolean}){
 const [tab,setTab]=useState('expert'),[mode,setMode]=useState<typeof modes[number]>('Technology'),[question,setQuestion]=useState(''),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[session,setSession]=useState(''),[count,setCount]=useState(0),[leadOpen,setLeadOpen]=useState(false),[captured,setCaptured]=useState(false),[source,setSource]=useState<Citation|null>(null),[assessment,setAssessment]=useState<any>(null),[launcher,setLauncher]=useState(false);
 useEffect(()=>{setSession(crypto.randomUUID())},[]);
 async function ask(q:string){if(q.trim().length<8||busy)return;setBusy(true);setError('');try{const data=await request('/api/chat',{question:q,mode,session_id:session});setMessages(m=>[...m,{question:q,answer:data.answer,citations:data.citations}]);setQuestion('');if(data.substantive){setCount(c=>c+1);if(count+1>=3&&!captured)setLeadOpen(true)}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function assess(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=Object.fromEntries(new FormData(e.currentTarget));try{setAssessment(await request('/api/assessment',form))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveLead(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await request('/api/leads',{...Object.fromEntries(new FormData(e.currentTarget)),consent:true,session_id:session});setCaptured(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const active=modeInfo[modes.indexOf(mode)];
 return <div className={compact?'app compact':'app'}>
 {!compact&&<header className="header"><a href="/" className="brand"><img src="/logo.svg" alt="Net Zero Platforms" width="215" height="50"/></a><nav><a href="https://www.nzp.technology" target="_blank" rel="noreferrer">Explore NZP <ArrowUpRight size={14}/></a><a href="/admin" className="admin-link">Admin</a><button className="outline small" onClick={()=>setLeadOpen(true)}>Talk to our team <ArrowUpRight size={15}/></button></nav></header>}
 <div className="shell"><aside className="sidebar"><a className="product-brand" href="/"><span className="icon-box"><Atom size={23}/></span><span>Ask NZP Expert<sup>™</sup><small>ENGINEERING INTELLIGENCE</small></span></a><p className="side-label">YOUR WORKSPACE</p><button className={tab==='expert'?'side-item selected':'side-item'} onClick={()=>setTab('expert')}><MessageSquare size={18}/> Expert conversation</button><button className={tab==='assessment'?'side-item selected':'side-item'} onClick={()=>setTab('assessment')}><ChartNoAxesCombined size={18}/> Feedstock assessment <span className="tiny">BETA</span></button><div className="side-rule"/><p className="side-label">SPECIALIST EXPERTS</p>{modes.map((m,i)=>{const Icon=modeInfo[i].icon;return <button key={m} className={'side-item '+(mode===m?'mode-selected':'')} onClick={()=>{setMode(m);setTab('expert')}}><Icon size={18}/>{m}<ChevronRight className="chevron" size={14}/></button>})}<div className="evidence-note"><ShieldCheck size={22}/><h4>Evidence comes first.</h4><p>Guidance grounded in NZP-approved sources. Every supported answer is traceable.</p><span>NZP KNOWLEDGE PLATFORM</span></div><button className="new-chat" onClick={()=>{setMessages([]);setCount(0);setError('');setSession(crypto.randomUUID())}}><Plus size={17}/> New conversation</button></aside>
 <main id="main"><div className="topbar"><span>{tab==='expert'?'Expert workspace':'Project screening'} <ChevronRight size={13}/> {tab==='expert'?mode:'Feedstock assessment'}</span><span className="review-badge"><i/> Evidence-led guidance</span></div>
 {tab==='expert'?<><section className="intro"><div className="eyebrow"><span/> FROM WASTE TO POSSIBILITY</div><h1>Your questions.<br/><em>Our specialist expertise.</em></h1><p>Explore the technology, understand your feedstock, and shape your<br className="desktop"/> waste-to-value opportunity — one informed conversation at a time.</p></section>
 <div className="mode-grid">{modes.map((m,i)=>{const Icon=modeInfo[i].icon;return <button key={m} className={'mode-card '+(mode===m?'active':'')} onClick={()=>setMode(m)}><div><Icon size={23}/>{mode===m?<span className="active-dot"/>:<ArrowUpRight size={15}/>}</div><strong>{m}</strong><small>{modeInfo[i].desc}</small></button>})}</div>
 <section className="conversation"><div className="conversation-head"><span className="mini-icon"><active.icon size={20}/></span><div><strong>{mode} Expert</strong><small>Specialist guidance. Supported by evidence.</small></div><span className="pill">NZP EXPERT</span></div>
 {messages.length===0?<div className="welcome"><h3>Let’s explore what’s possible.</h3><p>Ask a question about {mode.toLowerCase()}, or start with one of these.</p><div className="suggestions">{[active.question,'What evidence is needed to evaluate my project?','How can I get a preliminary feedstock assessment?'].map(q=><button disabled={busy} key={q} onClick={()=>q.includes('preliminary')?setTab('assessment'):ask(q)}>{q}<ArrowRight size={16}/></button>)}</div></div>:<div className="messages" aria-live="polite">{messages.map((m,i)=><article key={i}><div className="user-message">{m.question}</div><div className="answer"><span className="answer-label"><Atom size={16}/> NZP EXPERT</span><p>{m.answer}</p>{m.citations.length>0&&<div className="citations">{m.citations.map((c,j)=><button key={c.id} onClick={()=>setSource(c)}><FileText size={14}/> {j+1}. {c.title}</button>)}</div>}</div></article>)}</div>}
 {busy&&<p className="working" role="status">Reviewing the evidence…</p>}{error&&<p role="alert" className="error">{error}</p>}<form className="composer" onSubmit={e=>{e.preventDefault();ask(question)}}><label className="sr-only" htmlFor="question">Your question</label><textarea id="question" value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)} placeholder={`Ask the NZP ${mode.toLowerCase()} expert…`} rows={2}/><button aria-label="Send question" disabled={busy||question.trim().length<8||!session}><ArrowRight size={21}/></button><div className="composer-footer"><span><ShieldCheck size={13}/> Answers use approved NZP evidence</span><span>{question.length}/2000</span></div></form></section>
 <div className="assessment-teaser"><span className="mini-icon"><ChartNoAxesCombined size={22}/></span><div><strong>Have a waste stream in mind?</strong><p>Start with your feedstock. Explore your project’s potential.</p></div><button onClick={()=>setTab('assessment')}>Assess your feedstock <ArrowUpRight size={17}/></button></div></>:<><section className="intro"><div className="eyebrow"><span/> MODEL FIRST. INVEST LATER.</div><h1>Start with your feedstock.<br/><em>Explore the opportunity.</em></h1><p>A preliminary screening built around your material, location and scale.<br/>Numerical outputs require validated NZP model assumptions.</p></section><div className="assessment-layout"><form className="panel assessment-form" onSubmit={assess}><h3>Your feedstock profile</h3><label>Feedstock type<select name="feedstock">{wasteTypes.map(w=><option key={w}>{w}</option>)}</select></label><div className="form-grid"><label>Annual tonnes<input name="tonnes" type="number" min="1" max="100000000" required placeholder="e.g. 28,000"/></label><label>Country<input name="country" required minLength={2} placeholder="e.g. United Kingdom"/></label></div><div className="form-grid"><label>Moisture content (%)<input name="moisture" type="number" min="0" max="100" required placeholder="From laboratory analysis"/></label><label>Revenue pathway<select name="pathway"><option value="hydrogen">Hydrogen</option><option value="co">Carbon monoxide</option><option value="syngas">Syngas</option></select></label></div><label>Relevant characteristics<textarea name="characteristics" maxLength={2000} required placeholder="Composition, contamination, calorific value, seasonal variation and current treatment…" rows={4}/></label><button className="primary" disabled={busy}>{busy?'Reviewing…':'Run preliminary assessment'}<ArrowRight size={17}/></button>{error&&<p className="error" role="alert">{error}</p>}</form><div className="panel result-panel"><span className="pill">INDICATIVE • PRELIMINARY</span><h3>Your opportunity, with evidence.</h3><p>{assessment?.message||'Enter your waste profile to check whether an approved NZP model is available for your project.'}</p><div className="output-grid">{[['Syngas','syngas','Nm³/year'],['Hydrogen','hydrogen','kg/year'],['Carbon monoxide','co','kg/year'],['Revenue potential','revenue',assessment?.currency||'currency/year'],['Carbon savings','carbon','tCO₂e/year'],['Indicative ROI','roi','% annual']].map(([label,key,unit])=><div key={key}><small>{label}</small><strong>{assessment?.outputs?Number(assessment.outputs[key]).toLocaleString(undefined,{maximumFractionDigits:1}):'—'}</strong><span>{assessment?.outputs?unit:'Awaiting validated factors'}</span></div>)}</div>{assessment?.outputs&&<p>Model: {assessment.model}<br/>Uncertainty: ±{assessment.uncertainty_percent}%<br/>Assumptions: {assessment.assumptions}</p>}<button className="outline" onClick={()=>setLeadOpen(true)}>Request an engineering review <ArrowUpRight size={16}/></button></div></div></>}
 <footer><span>© {new Date().getFullYear()} Net Zero Platforms</span><span>Indicative guidance • Project-specific validation required</span><a href="/privacy">Privacy</a></footer></main></div>
 {!compact&&<><button className="launcher" aria-label="Open compact expert" onClick={()=>setLauncher(!launcher)}>{launcher?<X size={18}/>:<MessageSquare size={18}/>} Ask NZP Expert™</button>{launcher&&<div className="widget"><div className="widget-title">Ask NZP Expert™ <button aria-label="Close compact expert" onClick={()=>setLauncher(false)}><X size={18}/></button></div><iframe title="NZP compact expert" src="/embed"/></div>}</>}
 {leadOpen&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="lead-title"><button className="close" aria-label="Close contact form" onClick={()=>{setLeadOpen(false);setError('')}}><X size={20}/></button>{captured?<><CheckCircle2 className="success-icon" size={35}/><h2 id="lead-title">Your project is with us.</h2><p>Your details have been saved for the NZP team to review.</p><button className="primary" onClick={()=>setLeadOpen(false)}>Continue exploring</button></>:<><span className="eyebrow">LET’S SHAPE YOUR PROJECT</span><h2 id="lead-title">Take the next step.</h2><p>Tell us a little about your opportunity. The NZP team can help turn your questions into a project-specific conversation.</p><form onSubmit={saveLead}><div className="form-grid">{[['Name','name'],['Company','company'],['Email','email'],['Country','country']].map(([label,name])=><label key={name}>{label}<input name={name} type={name==='email'?'email':'text'} required minLength={name==='email'?undefined:2} maxLength={150}/></label>)}<label>Waste type<select name="waste_type">{wasteTypes.map(w=><option key={w}>{w}</option>)}</select></label><label>Annual tonnes<input name="annual_tonnes" type="number" min="1" max="100000000" required/></label></div><label className="consent"><input type="checkbox" required/> I agree to NZP using these details to respond to my enquiry, as explained in the <a href="/privacy">privacy notice</a>.</label>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>Send project enquiry <ArrowRight size={17}/></button></form></>}</section></div>}
 {source&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Source evidence"><button className="close" aria-label="Close evidence" onClick={()=>setSource(null)}><X size={20}/></button><span className="eyebrow">SOURCE EVIDENCE</span><h2>{source.title}</h2><p>{source.locator}</p><blockquote>{source.excerpt}</blockquote><a href={source.url} target="_blank" rel="noreferrer">Open source <ArrowUpRight size={15}/></a></section></div>}
 </div>
}
