export const solutions = [
{slug:'waste-resource-recovery',number:'01',label:'Waste & resource recovery',title:'A residual stream. A new starting point.',short:'Find a productive route for materials that cannot reasonably be reused or recycled.',problem:'Disposal dependency, variable treatment costs and long-term residual volumes can make resource management difficult to plan.',approach:'NZP screens the residual fraction, establishes what preparation is needed and compares practical syngas-led routes with the current treatment baseline.',feedstocks:['Industrial carbon-bearing residuals','Qualified RDF / SRF','Mixed commercial residuals','Biogenic process residues'],outputs:['Conditioned syngas','Power and recoverable heat','Hydrogen and CO','Potential recovered metals and vitrified material'],checks:['Representative composition and variability','Moisture, ash, calorific value and contaminants','Treatment permits and emissions controls','Residue testing and product acceptance'],value:'Connect treatment needs with local product demand, rather than selecting a disposal route in isolation.',cta:'Assess my residual stream'},
{slug:'power-heat',number:'02',label:'Firm power & heat',title:'Make local resources work for local demand.',short:'Assess controllable electricity and useful heat from qualified residual feedstock.',problem:'Industrial sites need reliable energy at a cost they can plan around. Local residual resources may offer an additional supply pathway.',approach:'Cleaned syngas can be configured for industrial engines or turbines. NZP evaluates useful heat recovery, internal electrical loads and the net energy available to the customer.',feedstocks:['Qualified industrial residuals','RDF / SRF','Biogenic residues'],outputs:['Controllable electricity','Useful process heat','Combined heat and power'],checks:['Hourly electricity and heat demand','Gas quality and equipment compatibility','Grid connection and operating profile','Gross generation versus internal plant consumption'],value:'Explore co-location, energy resilience and heat integration against your actual demand profile.',cta:'Assess my energy requirement'},
{slug:'hydrogen-co',number:'03',label:'Hydrogen & CO',title:'Keep the molecule in the value chain.',short:'Configure conditioned syngas around industrial hydrogen, carbon monoxide or mixed-gas demand.',problem:'Molecule users need defined purity, pressure, volume and delivery conditions. A useful production route must meet those specifications consistently.',approach:'NZP considers gas cleaning, conditioning and separation around the customer’s requirement. Hydrogen separation and the hydrogen-to-CO ratio are engineered for the selected pathway.',feedstocks:['Qualified carbon-bearing residuals','Industrial waste blends','Biogenic feedstock'],outputs:['Industrial hydrogen','Carbon monoxide','Conditioned H₂ / CO-rich syngas'],checks:['Product purity, pressure and impurity limits','Continuous versus variable offtake','Hydrogen recovery and conditioning requirements','Lifecycle carbon assessment and electricity sourcing'],value:'Investigate local production alongside existing supply, with specification and offtake at the centre of the project.',cta:'Assess my molecule requirement'},
{slug:'fuels-chemicals',number:'04',label:'Fuels & chemicals',title:'An intermediate with further possibilities.',short:'Prepare syngas for third-party fuel and chemical synthesis pathways.',problem:'Fuel and chemical producers need consistent synthesis feedstock and a credible route through integration, certification and commercial offtake.',approach:'NZP develops the conversion and syngas preparation architecture. Specialist downstream licensors and partners supply the synthesis technology for the chosen end product.',feedstocks:['Qualified non-recyclable carbon-bearing material','Biogenic residues','Qualified blended feedstock'],outputs:['Synthesis-grade syngas','Potential methanol pathway','Potential synthetic fuel pathway','Potential ammonia pathway via hydrogen'],checks:['Downstream licensor gas specification','Contaminant limits and catalyst protection','Scale and continuous supply','Carbon intensity, product eligibility and certification'],value:'Compare downstream value without assuming that every fuel pathway is technically or economically suitable.',cta:'Discuss a fuels or chemicals project'},
{slug:'industrial-clusters',number:'05',label:'Industrial clusters',title:'Connect the things that belong together.',short:'Bring residual streams, industrial demand and infrastructure into one project.',problem:'One site may have a residual stream, another a heat requirement and a third a molecule offtake. The value lies in connecting them with the right infrastructure.',approach:'NZP assesses industrial co-location and shared utilities, matches feedstock supply to offtake and develops a phased conversion configuration.',feedstocks:['Industrial cluster residuals','Qualified process byproducts','Blended local feedstock'],outputs:['Industrial syngas','Hydrogen and CO','Shared power and heat','Potential material recovery'],checks:['Feedstock and offtake agreements','Shared utilities and site constraints','Distribution distances and costs','Operating interfaces and responsibility allocation'],value:'Build an integrated commercial case around local relationships, logistics and demand.',cta:'Develop a cluster project'},
{slug:'regional-energy',number:'06',label:'Regional energy & resources',title:'Create value closer to its source.',short:'Explore regional projects that connect resource management with energy resilience.',problem:'Regional waste and energy needs are often planned separately. A coordinated project may create local value, but must fit its community and regulatory setting.',approach:'NZP works with developers and strategic partners to screen residual supply, suitable sites, local demand and the practical development pathway.',feedstocks:['Qualified regional residuals','Agricultural and biogenic residues','Qualified commercial material'],outputs:['Local power and heat','Industrial molecules where demand exists','Potential recovered materials'],checks:['Waste hierarchy and feedstock availability','Community engagement and planning','Local energy and product demand','Permits, transport and whole-system carbon assessment'],value:'Evaluate local resource use, infrastructure investment and industrial development together.',cta:'Explore a strategic partnership'}
];
export const processSteps = [
['Recycle first','Recover the materials that should be reused or recycled.'],
['Qualify residuals','Understand composition, volume, moisture and contaminants.'],
['Convert','A sealed conversion core uses ultra-high temperature plasma technology to create raw syngas.'],
['Clean & condition','Industrial modules prepare the gas for its intended application.'],
['Configure outputs','Match practical energy and molecule pathways to local demand.']
];
export const stages = [
['Screen','Define the opportunity','Your materials, location, current treatment route and required products establish the starting point.','Initial technical and commercial screen'],
['Model','Compare practical configurations','Mass and energy balances, feedstock variability, utility requirements and revenue assumptions help narrow the options.','Configuration and sensitivity assessment'],
['Validate','Test the assumptions','Feedstock trials, product specification, emissions, residues, carbon performance and engineering are checked at the relevant scale.','Documented validation programme'],
['Develop','Assemble the project','Align site, planning, permits, delivery partners, supply contracts, offtake and capital requirements.','Project development and investment case'],
['Deploy','Integrate and commission','Subject to approvals and commercial agreements, deliver the chosen architecture with defined interfaces and acceptance testing.','Integrated technology deployment']
];
export const evidence = [
{tag:'Established',title:'Industrial building blocks',description:'Submerged-arc furnace principles, electrodes, industrial gas cleaning, separation and synthesis each have established industrial applications.',limit:'Component maturity does not establish the performance of an integrated NZP project.',items:['Industrial furnace architecture','Commercial gas-processing equipment','Established downstream process families']},
{tag:'Historical',title:'Technology heritage',description:'NZP describes its engineering heritage in demanding hazardous-waste treatment and ultra-high temperature plasma technology programmes.',limit:'Historical systems and regulatory approvals must be tied to the specific system, application and period. They do not transfer automatically to a new project.',items:['Relevant operating history','Application-specific treatment evidence','Historical engineering records']},
{tag:'Engineering',title:'NZP project architecture',description:'Process configuration, modelling and engineering know-how connect the conversion core with site utilities and downstream output requirements.',limit:'Models inform decisions; results require review against measured data and the proposed design.',items:['Mass and energy balances','Equipment interfaces','Techno-economic models']},
{tag:'Project-specific',title:'The case for your project',description:'Feedstock, net energy, product quality, emissions, residues, costs and lifecycle carbon must be assessed for the actual project.',limit:'Yield, availability, payback and carbon benefits are project-specific outcomes, not universal promises.',items:['Representative feedstock trials','Product and environmental testing','Independent review where appropriate']}
];
export const insights = [
{slug:'why-syngas',category:'Molecules',title:'Why syngas keeps your options open',intro:'The decision between power, hydrogen and chemical feedstock starts with the intermediate.',sections:[['What syngas is','Synthesis gas is a mixture containing hydrogen and carbon monoxide, together with other constituents whose concentrations depend on feedstock and process conditions. Raw gas normally needs cleaning and conditioning before use.'],['Why the intermediate matters','Combustion primarily converts chemical energy into heat. A gasification route creates a gas intermediate that may be used for power or processed further. This preserves choices, but each choice adds specific equipment, efficiency losses and commercial requirements.'],['Start with demand','The highest quoted product price is not automatically the best pathway. Local demand, product specification, scale, operating availability and downstream capital all influence the practical result. NZP begins with those conditions.']]},
{slug:'feedstock-first',category:'Project development',title:'What makes a residual stream worth screening?',intro:'A representative sample and a realistic supply profile are more useful than a headline tonnage.',sections:[['Composition comes first','Record moisture, ash, calorific value, carbon-bearing fractions and relevant contaminants. Identify where the data came from and how variable the stream is. A single favourable sample may not represent year-round operations.'],['Volume needs a time dimension','Annual tonnage is only a starting point. Seasonality, minimum committed volumes, interruptions, preparation requirements and transport distance affect the design and commercial case.'],['The baseline matters','Compare the proposed route with what really happens today: treatment destination, net cost, regulatory obligations and existing recovery. Waste-to-Value should be assessed within the waste hierarchy, after practical reuse and recycling.']]},
{slug:'carbon-boundary',category:'Carbon & evidence',title:'A carbon claim needs a system boundary',intro:'Feedstock, electricity and the fate of the product all change the answer.',sections:[['Look beyond the conversion core','Include feedstock preparation and transport, purchased electricity, process utilities, gas cleaning, downstream conversion and the use or disposal of products and residues. Compare with a defined baseline.'],['Biogenic and fossil carbon differ','Waste streams may contain both biogenic and fossil carbon. Renewable status, fuel eligibility and carbon accounting cannot be inferred from the word waste. They depend on composition and the relevant methodology.'],['Capture is a separate pathway','Carbon capture may be evaluated where practical. Capture efficiency, energy demand, transport and permanent storage all need to be included. Carbon credits and negative emissions are not automatic project revenues.']]},
{slug:'industrial-co-location',category:'Industrial integration',title:'Why the site can matter as much as the feedstock',intro:'Utilities, logistics and nearby customers can shape the economics before technology selection.',sections:[['Build around useful demand','Heat only creates value when a customer can use its temperature level, volume and timing. Molecules need a defined specification and supply interface. Co-location can help, but does not remove these constraints.'],['Check infrastructure early','Electricity connection, water, access, land, planning constraints and space for preparation, gas processing and residue management all affect feasibility.'],['Give every interface an owner','Feedstock supply, conversion, gas conditioning, synthesis, distribution and offtake may involve different organisations. A project becomes more credible when responsibilities, performance conditions and acceptance tests are explicit.']]}
];
export const faqs=[
['Is this a replacement for recycling?','No. NZP starts with reuse and recycling, then screens the remaining residual fraction. The project must respect the waste hierarchy and applicable local requirements.'],
['Can NZP process any waste?','Suitability must be established. Carbon content, moisture, ash, contaminants, preparation requirements and variability affect the process. Mineral-only material does not automatically become syngas. Specialist or hazardous streams need specific treatment validation and permits.'],
['Does gasification mean zero emissions?','No. The complete project includes preparation, conversion, utilities, gas conditioning and downstream use. Emissions control and a project-specific lifecycle assessment are required.'],
['Can the plant produce hydrogen, power and fuels at once?','The architecture can be configured around selected pathways, subject to scale and engineering. A syngas stream cannot be allocated in full to several outputs at the same time; mass and energy balances must reflect the chosen split.'],
['Are returns or carbon credits guaranteed?','No. Costs, product prices, availability, feedstock contracts and carbon eligibility are assessed for the specific project. Public screening tools are not an investment case or a performance guarantee.'],
['What should I send for an initial screen?','Your organisation and location, feedstock type and annual volume, current treatment route, any available composition analysis, site information and the energy or molecule demand you want to address. Unknowns are acceptable at the initial stage.'],
['Can legacy coal or mineral residues be considered?','They may be considered as specialist opportunities. Coal-bearing material, ash and mineral tailings are different feedstocks. Usable carbon, contaminants, residue acceptance, treatment obligations and permitting need separate assessment. Liability transfer is a legal and commercial structure, not an automatic consequence of treatment.'],
['How are partners selected?','A project may require furnace and equipment suppliers, engineering contractors, downstream licensors, product offtakers and capital partners. Responsibilities and contractual status are established for each project. No supplier relationship is implied by a technology category.']
];
