import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import MoveUpRight from 'lucide-react/dist/esm/icons/move-up-right.js';
import Download from 'lucide-react/dist/esm/icons/download.js';
import Plus from 'lucide-react/dist/esm/icons/plus.js';
import {sections} from './sections.js';
export default function Expansion({slug}){
 const section=sections.find(s=>s.slug===slug);
 const [query,setQuery]=useState('');
 const items=section.items.filter(i=>`${i.title} ${i.description} ${i.inputs.join(' ')}`.toLowerCase().includes(query.toLowerCase().trim()));
 return <><section className="page-hero"><div className="container"><div className="eyebrow"><span/>{section.eyebrow}</div><h1>{section.title}</h1><p>{section.description}</p><div className="button-row section-hero-actions"><Link className="button" to="/start">Discuss your project<MoveUpRight size={16}/></Link><a className="text-link" href={`/nzp-${slug}-guide.txt`} download><Download size={17}/>Download this guide</a></div></div></section>
 <div className="directory-bar"><div className="container"><span className="small-label">Explore NZP</span><div>{sections.map(s=><Link key={s.slug} to={`/${s.slug}`} aria-current={s.slug===slug?'page':undefined}>{s.label}</Link>)}</div></div></div>
 <section className="section container"><div className="section-head"><div><div className="eyebrow"><span/>From opportunity to evidence</div><h2>{slug==='resources'?'Start with a useful checklist.':'Find your starting point.'}</h2></div><label className="directory-search"><span>Search {section.label.toLowerCase()}</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search topics or requirements"/></label></div><p className="catalogue-count" role="status">{items.length} {items.length===1?'topic':'topics'}{query&&` matching “${query}”`}</p>
 <div className="catalogue-grid">{items.map(i=><article className="catalogue-card" key={i.title}><span className="small-label">{String(section.items.indexOf(i)+1).padStart(2,'0')} / {section.label}</span><h2>{i.title}</h2><p>{i.description}</p><details><summary>What to establish<Plus size={17}/></summary><ul>{i.inputs.map(input=><li key={input}>{input}</li>)}</ul></details><div className="catalogue-links">{i.route?<Link className="text-link" to={`/solutions/${i.route}`}>Explore the solution<MoveUpRight size={16}/></Link>:<Link className="text-link" to="/start">Discuss this opportunity<MoveUpRight size={16}/></Link>}</div></article>)}</div>
 {!items.length&&<div className="catalogue-empty"><h3>No matching topics</h3><p>Try another term or browse all the topics.</p><button className="button secondary" onClick={()=>setQuery('')}>Clear search</button></div>}
 <div className="note"><p>{section.note}</p></div>
 {slug==='ai-modelling'&&<div className="mini-cta"><div><h2>Test an illustrative scenario.</h2><p>Change treatment income, net energy sales, costs and capital. See the arithmetic update as you change each assumption.</p></div><Link className="button" to="/economics">Open the economics tool<MoveUpRight size={16}/></Link></div>}
 {slug==='technology-ip'&&<div className="mini-cta"><div><h2>Understand the validation pathway.</h2><p>Separate established industrial components, historical experience and project-specific evidence.</p></div><Link className="button" to="/evidence">Explore the evidence<MoveUpRight size={16}/></Link></div>}
 {slug==='resources'&&<section className="resource-library"><div className="eyebrow"><span/>Download library / Plain-text guides</div><h2>Take the next discussion with you.</h2><div className="resource-grid"><a href="/nzp-project-guide.txt" download className="resource-link"><span>Project Screening Guide<small>Core inputs and validation checklist</small></span><Download size={22}/></a>{sections.filter(s=>s.slug!=='resources').map(s=><a key={s.slug} href={`/nzp-${s.slug}-guide.txt`} download className="resource-link"><span>{s.label}<small>Introductory guide · Plain text</small></span><Download size={22}/></a>)}</div><div className="resource-related"><Link className="text-link" to="/insights">Read explanatory articles<MoveUpRight size={16}/></Link><Link className="text-link" to="/evidence">Review the evidence framework<MoveUpRight size={16}/></Link></div></section>}
 </section><section className="cta"><div className="container"><div><div className="eyebrow"><span/>Bring your starting point</div><h2>Let’s connect the material<br/>with the opportunity.</h2><p>Share your feedstock, site or product requirement for an initial technical and commercial discussion.</p></div><Link className="button" to="/start">Start a project discussion</Link></div></section></>;
}
